{
  inputs = {
    utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };
  outputs = { nixpkgs, utils, ... }: utils.lib.eachDefaultSystem (system:
    let
      pkgs = nixpkgs.legacyPackages.${system};
    in
    {
      devShell = pkgs.mkShell {
        name = "rust";
        
        packages = with pkgs; [
          bacon  # Background rust code checker
          cargo  # Downloads your Rust project's dependencies and builds your project
          cargo-cache  # manage cargo cache
          #cargo-deny  # list of all licenses for a crate
          #cargo-hack  # provide various options useful for testing and continuous integration
          cargo-outdated  #display out of date Rust dependencies
          cargo-sweep  # cleaning up unused build files generated by Cargo
          rustc  # Safe, concurrent, practical language
          rust-analyzer  # Modular compiler frontend for the Rust language
          rustfmt  # Tool for formatting Rust code according to style guidelines
          clippy  # rust linter

          # gdb  # GNU Project debugger
          lldb # Next-generation high-performance debugger
        ];
        
      	shellHook = ''

          # shell enhancers
          function cargo-new(){
            cargo new $@
            cd $@
            l
          }
          alias cn='cargo-new'
          alias cr='clear && cargo run'
          alias ct='clear && cargo test'
          alias cc='clear && cargo check'
          alias cc='clear && cargo flamegraph'
          alias cc='clear && cargo tree'
          alias cc='clear && cargo check'
          alias cc='clear && cargo check'

          # print out environment for user
          echo -e "\e[1;94m == Rust Development Environment =="
        	cargo --version
          rustc --version
          rust-analyzer --version
          rustfmt --version
          cargo clippy --version

          # print out aliases
          alias | rg "cargo"
    		  echo -e "\e[0m"

          # open dotfiles in editor
          "$EDITOR" "$DOTFILES"
    	  '';
      };
    }
  );
}
